### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Ulrik-dk** [Ulrik-dk/segmented#1]
- [ ] In segmented scan, can you replace `x_flag || y_flag` with just `y_flags`, and is it faster? Do benchmarks.
- [ ] Interpreter vs compiler incongruence. Einar, isolate the problem.
- [ ] Make issue on futhark pkg timestamping. Ulrik.
- [ ] Can the other segmented operations be optimized?
- [ ] Add segmented_replicate, which is taken from the website.
- [ ] Head-flag in flag arrays? Einar please explain in a comment here.
```
def segmented_replicate [n] 't (revaluation_point_2d:[n]i64) (vs:[n]t) : []t =
    let idxs = replicated_iota revaluation_point_2d
    in map (\i -> vs[i]) idxs
```

Don't bother with these unless we will need them:
- [ ] Are there other segmented operations in https://futhark-book.readthedocs.io/en/latest/regular-flattening.html that are not in the library?
- [ ] Melsman added an exclusive-segmented-scan in an issue four years ago in the original repo, which was not added.
